[package]
name = "hello_contract"
version = "0.0.1"
authors = ["Alex Aunter <lxaunter@gmail.com"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "3.1.0"

[profile.release]
codegen-units=1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
